name: 签到

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 */6 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r requirements.txt
        string="${{ secrets.COOKIE }}"
        IFS="#"
        array=($string)
        for var in ${array[@]}
        do
          python3 checkin.py <<EOF
          $var
        EOF
        done
        
